# åŸºç¡€é…ç½®
baseurl = "https://crownjoker07.github.io/"
languageCode = "zh-cn"
theme = "hugo-theme-stack"
title = "ZZWBlog"
copyright = "ZhuangZewei"
DefaultContentLanguage = "zh-cn"
hasCJKLanguage = false

# å¤šè¯­è¨€é…ç½®
[languages.zh-cn]
languageName = "ä¸­æ–‡"
title = "åº„æ³½ä¼Ÿçš„åšå®¢"
weight = 1
[languages.zh-cn.params.sidebar]
subtitle = "ä¸€åªä¹Œé¸¦çš„è‡ªç™½"

# æœåŠ¡é›†æˆ
[services.disqus]
shortname = "hugo-theme-stack"
[services.googleAnalytics]

# å†…å®¹ç®¡ç†
[pagination]
pagerSize = 10
[permalinks]
post = "/p/:slug/"
page = "/:slug/"

# ä¸»é¢˜å‚æ•°
## å…¨å±€å‚æ•°
[params]
favicon = "favicon/favicon.ico"
mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true

[params.footer]
since = 2_025

[params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

## ä¾§è¾¹æ è®¾ç½®
[params.sidebar]
emoji = "ğŸ˜„"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/avatar.png"

## æ–‡ç« é¡µé¢
[params.article]
math = false
toc = true
readingTime = true

[params.article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

# è¯„è®ºç³»ç»Ÿ
# [params.comments]
# enabled = true
# provider = "disqus"

# [params.comments.disqusjs]

# [params.comments.utterances]
# issueTerm = "pathname"

# [params.comments.beaudar]
# issueTerm = "pathname"

# [params.comments.remark42]

# [params.comments.vssue]
# autoCreateIssue = false

# [params.comments.waline]
# emoji = ["https://unpkg.com/@waline/emojis@1.0.1/weibo"]
# requiredMeta = ["name", "email", "url"]

# [params.comments.waline.locale]
# admin = "Admin"

# [params.comments.twikoo]

# [params.comments.cactus]
# defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
# serverName = "cactus.chat"
# siteName = ""

# [params.comments.giscus]
# reactionsEnabled = 1
# emitMetadata = 0

# [params.comments.gitalk]

# [params.comments.cusdis]

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[params.opengraph.twitter]
card = "summary_large_image"

[params.defaultImage.opengraph]
enabled = false
local = false

[params.colorScheme]
toggle = true
default = "auto"

[params.imageProcessing.cover]
enabled = true

[params.imageProcessing.content]
enabled = true

# èœå•é…ç½®
[menu]
main = []


[[menu.social]]
identifier = "Bilibili"
name = "Bilibili"
url = "https://space.bilibili.com/106612965"
weight = 1
[menu.social.params]
icon = "brand-bilibili"

[[menu.social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/CrownJoker07"
weight = 2
[menu.social.params]
icon = "brand-github"

# å†…å®¹å…³è”
[related]
includeNewer = true
threshold = 60
toLower = false

[[related.indices]]
name = "tags"
weight = 100

[[related.indices]]
name = "categories"
weight = 200

# Markdown æ¸²æŸ“
[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [["\\[", "\\]"], ["$$", "$$"]]
inline = [["\\(", "\\)"]]

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
